# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 405bb8b59d44fae4469c8c449bfeab6ffaa2013cad98a3f1759f7c40e8e0d5910e2b33b7b43610ed69e01d45ff3a27d0cb3e2517ab7a73b15c1c84739b744b54

test:
  secret_key_base: 7a367eb0858b83f6e115f72f91999db1af4a4068ce47c714e5758591ba3d55f7521f77809b589fd8def5bbd5da74b4e8ffdc09bf61c52e2bac8d1c2f6c5c8395

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
